# Generated by Django 4.2.4 on 2023-08-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='header')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug')),
                ('content', models.TextField(blank=True, null=True, verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='catalog/', verbose_name='image')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date_of_creation')),
                ('is_published', models.BooleanField(default=False, verbose_name='published')),
                ('views_count', models.IntegerField(default=0, verbose_name='count_of_views')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
